/**
 * @module reel/sfx.generated
 * @description The advertisement's rendered sound effects.
 *
 * GENERATED by `scripts/make-sfx.mjs` from `sfx.json`.
 * Do not edit. Read this through `sfxClip` in `ad/sfx.ts`, never directly.
 */

/** Sound id -> the WAV that was rendered for it, and its measured duration. */
export const SFX = {
  drop: { file: 'drop.wav', seconds: 1.1 },
  whoosh: { file: 'whoosh.wav', seconds: 0.45 },
  click: { file: 'click.wav', seconds: 0.07 },
  tick: { file: 'tick.wav', seconds: 0.05 },
  impact: { file: 'impact.wav', seconds: 0.3 },
  swell: { file: 'swell.wav', seconds: 0.55 },
  latch: { file: 'latch.wav', seconds: 0.43 },
} as const;
