/**
 * @module reel/theme.generated
 * @description The app's design tokens, mirrored for the composition.
 *
 * GENERATED by `scripts/sync-theme.mjs` from `src/sidepanel/tailwind.css`.
 * Do not edit. Reel-only values belong in `theme.ts`, which re-exports this.
 */

export const COLOR = {
  primary: '#546be7',
  'primary-text': '#4c64e1',
  'primary-dark': '#2e40a5',
  'primary-light': '#f2f3fd',
  'primary-highlight': '#dbe0fa',
  danger: '#e72500',
  'danger-text': '#d92300',
  'danger-light': '#fff0ee',
  success: '#16884a',
  'success-text': '#197f48',
  'success-light': '#defae7',
  warning: '#a16c03',
  'warning-text': '#966603',
  'warning-light': '#fdfad9',
  info: '#546be7',
  'info-light': '#f2f3fd',
  accent: '#9333ea',
  'accent-dark': '#7e22ce',
  canvas: '#f4f4f4',
  'neutral-50': '#f4f4f4',
  'neutral-100': '#ededed',
  'neutral-200': '#e1e1e1',
  'neutral-300': '#cbcbcb',
  'neutral-400': '#aeaeae',
  'neutral-500': '#8d8d8d',
  'neutral-600': '#6e6e6e',
  'neutral-700': '#4b4b4b',
  'neutral-900': '#272727',
} as const;

export const DUR = {
  instant: '80ms',
  quick: '140ms',
  move: '220ms',
  travel: '320ms',
  tell: '500ms',
  'hover-intent': '400ms',
  press: '60ms',
} as const;

export const EASE = {
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
  entrance: 'cubic-bezier(0, 0, 0, 1)',
  exit: 'cubic-bezier(0.3, 0, 1, 1)',
  affirm: 'cubic-bezier(\n    0.2,\n    1.3,\n    0.4,\n    1\n  )',
  press: 'cubic-bezier(0.2, 0, 0.1, 1)',
  glide: 'cubic-bezier(0.3, 1.12, 0.5, 1)',
} as const;

export const FONT = {
  primary: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  heading: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  mono: "'Roboto Mono', SFMono-Regular, Consolas, 'Liberation Mono', monospace",
} as const;
