/**
 * @module reel/vo.generated
 * @description Measured narration durations, one entry per recorded act.
 *
 * GENERATED by `scripts/measure-vo.mjs` from `captures/vo/*.wav`.
 * Do not edit. Read this through `voClip`/`voMeta` in `vo.ts`, never directly.
 */

/** Act key -> the WAV `ffprobe` measured for it, and its duration in seconds. */
export const VO = {} as const;
