import type { CatalogEndpoint } from '../types';

const APP_ENDPOINTS: readonly CatalogEndpoint[] = [
  {
    id: 'apps.list',
    path: '/api/v1/apps',
    method: 'GET',
    group: 'apps',
    summary: 'Every app integration in the org, active and inactive.',
    collection: true,
    keywords: ['integrations', 'sso', 'inventory'],
  },
  {
    id: 'apps.get',
    path: '/api/v1/apps/{appId}',
    method: 'GET',
    group: 'apps',
    summary: 'One app — its sign-on mode, its settings, and a link to its access policy.',
    collection: false,
  },
  {
    id: 'apps.users',
    path: '/api/v1/apps/{appId}/users',
    method: 'GET',
    group: 'apps',
    summary: 'Who is assigned to this app, and the scope each assignment came from.',
    collection: true,
    keywords: ['assignments', 'access', 'who'],
  },
  {
    id: 'apps.users.get',
    path: '/api/v1/apps/{appId}/users/{userId}',
    method: 'GET',
    group: 'apps',
    summary: 'One assignment — its scope, its status, and the app-side profile it carries.',
    collection: false,
  },
  {
    id: 'apps.users.assign',
    path: '/api/v1/apps/{appId}/users',
    method: 'POST',
    group: 'apps',
    summary: 'Assign a user directly. Body carries the id and any app-side profile values.',
    collection: false,
  },
  {
    id: 'apps.users.unassign',
    path: '/api/v1/apps/{appId}/users/{userId}',
    method: 'DELETE',
    group: 'apps',
    summary: 'Remove a direct assignment. A group path, if one exists, still grants access.',
    collection: false,
  },
  {
    id: 'apps.groups',
    path: '/api/v1/apps/{appId}/groups',
    method: 'GET',
    group: 'apps',
    summary: 'Group assignments on this app. Add expand=group to embed each group.',
    collection: true,
  },
  {
    id: 'apps.groups.assign',
    path: '/api/v1/apps/{appId}/groups/{groupId}',
    method: 'PUT',
    group: 'apps',
    summary: 'Assign a group to this app, granting everyone in it access.',
    collection: false,
  },
  {
    id: 'apps.groups.unassign',
    path: '/api/v1/apps/{appId}/groups/{groupId}',
    method: 'DELETE',
    group: 'apps',
    summary: 'Remove a group assignment. Direct assignments survive it.',
    collection: false,
  },
  {
    id: 'apps.groupPush',
    path: '/api/v1/apps/{appId}/group-push/mappings',
    method: 'GET',
    group: 'apps',
    summary: 'Push-group mappings and their sync status. More truthful here than the groups list.',
    collection: true,
    keywords: ['push', 'sync', 'provisioning'],
  },
  {
    id: 'apps.lifecycle.activate',
    path: '/api/v1/apps/{appId}/lifecycle/activate',
    method: 'POST',
    group: 'apps',
    summary: 'Activate an app, restoring it to every assigned user’s dashboard.',
    collection: false,
  },
  {
    id: 'apps.lifecycle.deactivate',
    path: '/api/v1/apps/{appId}/lifecycle/deactivate',
    method: 'POST',
    group: 'apps',
    summary: 'Deactivate an app. Assignments are kept; sign-in through it stops.',
    collection: false,
  },
  {
    id: 'apps.tokens',
    path: '/api/v1/apps/{appId}/tokens',
    method: 'GET',
    group: 'apps',
    summary: 'Refresh tokens this OAuth app has issued.',
    collection: true,
    keywords: ['oauth', 'refresh', 'revoke'],
  },
] as const;

export default APP_ENDPOINTS;
