import type { CatalogEndpoint } from '../types';

const GROUP_ENDPOINTS: readonly CatalogEndpoint[] = [
  {
    id: 'groups.list',
    path: '/api/v1/groups',
    method: 'GET',
    group: 'groups',
    summary: 'Every group in the org, with the last time any membership on it changed.',
    collection: true,
    keywords: ['inventory', 'directory'],
  },
  {
    id: 'groups.create',
    path: '/api/v1/groups',
    method: 'POST',
    group: 'groups',
    summary: 'Create an Okta-sourced group. Body carries profile.name and profile.description.',
    collection: false,
  },
  {
    id: 'groups.get',
    path: '/api/v1/groups/{groupId}',
    method: 'GET',
    group: 'groups',
    summary: 'One group — its name, its type, and when its membership last moved.',
    collection: false,
  },
  {
    id: 'groups.update',
    path: '/api/v1/groups/{groupId}',
    method: 'PUT',
    group: 'groups',
    summary: 'Rename or re-describe a group. Only OKTA_GROUP type groups are editable.',
    collection: false,
  },
  {
    id: 'groups.delete',
    path: '/api/v1/groups/{groupId}',
    method: 'DELETE',
    group: 'groups',
    summary: 'Delete a group. Members keep their accounts and lose whatever it granted.',
    collection: false,
  },
  {
    id: 'groups.members.list',
    path: '/api/v1/groups/{groupId}/users',
    method: 'GET',
    group: 'groups',
    summary: "A group's members. Add expand=group-rules for per-member attribution.",
    collection: true,
    keywords: ['members', 'membership', 'who'],
    paramOverrides: {
      limit: {
        defaultValue: '1000',
        max: 1000,
        note: 'This endpoint defaults to 1000 for historical reasons, unlike the rest of the API. Okta recommends setting 200 explicitly.',
      },
    },
  },
  {
    id: 'groups.members.add',
    path: '/api/v1/groups/{groupId}/users/{userId}',
    method: 'PUT',
    group: 'groups',
    summary: 'Add one member. Takes no body, and is idempotent.',
    collection: false,
  },
  {
    id: 'groups.members.remove',
    path: '/api/v1/groups/{groupId}/users/{userId}',
    method: 'DELETE',
    group: 'groups',
    summary: 'Remove one member. A rule that matches them will add them back.',
    collection: false,
  },
  {
    id: 'groups.members.rules',
    path: '/api/v1/groups/{groupId}/users/{userId}/group-rules',
    method: 'GET',
    group: 'groups',
    summary: 'Which rules put this member in this group, if any did.',
    collection: false,
    keywords: ['attribution', 'why', 'rule'],
  },
  {
    id: 'groups.apps',
    path: '/api/v1/groups/{groupId}/apps',
    method: 'GET',
    group: 'groups',
    summary: 'Apps assigned to this group, and so to everyone in it.',
    collection: true,
  },
  {
    id: 'groups.roles',
    path: '/api/v1/groups/{groupId}/roles',
    method: 'GET',
    group: 'groups',
    summary: 'Admin roles this group grants to its members.',
    collection: false,
    keywords: ['admin', 'delegated'],
  },
] as const;

export default GROUP_ENDPOINTS;
