import type { CatalogEndpoint } from '../types';

const ORG_ENDPOINTS: readonly CatalogEndpoint[] = [
  {
    id: 'org.get',
    path: '/api/v1/org',
    method: 'GET',
    group: 'org',
    summary: 'Org metadata — its name, subdomain, and support settings.',
    collection: false,
    keywords: ['tenant', 'settings'],
  },
  {
    id: 'org.session.me',
    path: '/api/v1/sessions/me',
    method: 'GET',
    group: 'org',
    summary: 'The current browser session, and when it expires.',
    collection: false,
    keywords: ['whoami', 'session', 'login'],
  },
  {
    id: 'org.userSchema',
    path: '/api/v1/meta/schemas/user/default',
    method: 'GET',
    group: 'org',
    summary: 'The default user profile schema — every attribute, and who masters each.',
    collection: false,
    keywords: ['attributes', 'custom', 'profile', 'schema'],
  },
  {
    id: 'org.userTypes',
    path: '/api/v1/meta/types/user',
    method: 'GET',
    group: 'org',
    summary: 'User types in the org, each with its own profile schema.',
    collection: false,
  },
  {
    id: 'org.authenticators',
    path: '/api/v1/authenticators',
    method: 'GET',
    group: 'org',
    summary: 'Authenticators configured org-wide, and which are enabled.',
    collection: false,
    keywords: ['mfa', 'factors', 'fastpass'],
  },
  {
    id: 'org.devices',
    path: '/api/v1/devices',
    method: 'GET',
    group: 'org',
    summary: 'Enrolled devices and their posture. Add expand=user to embed their users.',
    collection: true,
    keywords: ['endpoints', 'managed', 'posture'],
  },
  {
    id: 'org.zones',
    path: '/api/v1/zones',
    method: 'GET',
    group: 'org',
    summary: 'Network zones — the IP and location sets policy rules name.',
    collection: true,
    keywords: ['ip', 'network', 'location'],
  },
  {
    id: 'org.trustedOrigins',
    path: '/api/v1/trustedOrigins',
    method: 'GET',
    group: 'org',
    summary: 'Origins allowed to make cross-origin calls or receive redirects.',
    collection: true,
    keywords: ['cors', 'redirect'],
  },
  {
    id: 'org.behaviors',
    path: '/api/v1/behaviors',
    method: 'GET',
    group: 'org',
    summary: 'Behaviour detection rules — new device, new location, velocity.',
    collection: false,
    keywords: ['risk', 'anomaly'],
  },
  {
    id: 'org.idps',
    path: '/api/v1/idps',
    method: 'GET',
    group: 'org',
    summary: 'Identity providers this org federates to, social and enterprise.',
    collection: true,
    keywords: ['federation', 'saml', 'social'],
  },
  {
    id: 'org.eventHooks',
    path: '/api/v1/eventHooks',
    method: 'GET',
    group: 'org',
    summary: 'Outbound webhooks — the alternative to polling the System Log.',
    collection: false,
    keywords: ['webhook', 'outbound'],
  },
  {
    id: 'org.inlineHooks',
    path: '/api/v1/inlineHooks',
    method: 'GET',
    group: 'org',
    summary: 'Hooks that pause a flow and let an external service change its outcome.',
    collection: false,
  },
  {
    id: 'org.roles',
    path: '/api/v1/iam/roles',
    method: 'GET',
    group: 'org',
    summary: 'Custom admin roles, each a named set of permissions.',
    collection: true,
    keywords: ['admin', 'permissions', 'delegated'],
  },
  {
    id: 'org.brands',
    path: '/api/v1/brands',
    method: 'GET',
    group: 'org',
    summary: 'Sign-in page and email customisation.',
    collection: true,
    keywords: ['theme', 'customisation', 'branding'],
  },
  {
    id: 'org.mappings',
    path: '/api/v1/mappings',
    method: 'GET',
    group: 'org',
    summary: 'Attribute mappings between Okta and an app profile, as expressions.',
    collection: true,
    keywords: ['transform', 'expression'],
  },
] as const;

export default ORG_ENDPOINTS;
