import type { CatalogEndpoint } from '../types';

const USER_ENDPOINTS: readonly CatalogEndpoint[] = [
  {
    id: 'users.list',
    path: '/api/v1/users',
    method: 'GET',
    group: 'users',
    summary: 'Every user in the org, newest first by default.',
    collection: true,
    keywords: ['people', 'accounts', 'directory'],
  },
  {
    id: 'users.create',
    path: '/api/v1/users',
    method: 'POST',
    group: 'users',
    summary: 'Create a user. Body carries profile, and optionally credentials.',
    collection: false,
    keywords: ['new', 'add', 'provision'],
  },
  {
    id: 'users.get',
    path: '/api/v1/users/{userId}',
    method: 'GET',
    group: 'users',
    summary: 'One user in full — profile, status, and the timestamps around it.',
    collection: false,
  },
  {
    id: 'users.update',
    path: '/api/v1/users/{userId}',
    method: 'POST',
    group: 'users',
    summary: 'Partial update. Attributes not named are left alone.',
    collection: false,
    keywords: ['edit', 'patch', 'profile'],
  },
  {
    id: 'users.replace',
    path: '/api/v1/users/{userId}',
    method: 'PUT',
    group: 'users',
    summary: 'Full replace. Attributes not named are cleared.',
    collection: false,
  },
  {
    id: 'users.delete',
    path: '/api/v1/users/{userId}',
    method: 'DELETE',
    group: 'users',
    summary:
      'Delete a deactivated user permanently. Run twice from ACTIVE: the first call deactivates.',
    collection: false,
  },
  {
    id: 'users.me',
    path: '/api/v1/users/me',
    method: 'GET',
    group: 'users',
    summary: 'Whoever this browser session belongs to.',
    collection: false,
    keywords: ['self', 'current', 'whoami'],
  },
  {
    id: 'users.groups',
    path: '/api/v1/users/{userId}/groups',
    method: 'GET',
    group: 'users',
    summary: "A user's group memberships. No attribution and no per-membership date.",
    collection: true,
  },
  {
    id: 'users.appLinks',
    path: '/api/v1/users/{userId}/appLinks',
    method: 'GET',
    group: 'users',
    summary: 'Apps as the user sees them on their dashboard, with each SSO link.',
    collection: false,
    keywords: ['dashboard', 'tiles', 'sso'],
  },
  {
    id: 'users.apps',
    path: '/api/v1/users/{userId}/clients',
    method: 'GET',
    group: 'users',
    summary: 'OAuth clients this user has granted a token to.',
    collection: false,
    keywords: ['oauth', 'consent', 'tokens'],
  },
  {
    id: 'users.grants',
    path: '/api/v1/users/{userId}/grants',
    method: 'GET',
    group: 'users',
    summary: 'OAuth scope grants the user has consented to.',
    collection: true,
    keywords: ['consent', 'scopes'],
  },
  {
    id: 'users.factors',
    path: '/api/v1/users/{userId}/factors',
    method: 'GET',
    group: 'users',
    summary: "A user's enrolled MFA factors. One call per user — there is no bulk form.",
    collection: false,
    keywords: ['mfa', 'authenticators', 'enrollment'],
  },
  {
    id: 'users.factors.catalog',
    path: '/api/v1/users/{userId}/factors/catalog',
    method: 'GET',
    group: 'users',
    summary: 'Factors this user is eligible to enrol, given org policy.',
    collection: false,
  },
  {
    id: 'users.roles',
    path: '/api/v1/users/{userId}/roles',
    method: 'GET',
    group: 'users',
    summary: 'Admin roles assigned to this user directly — not roles inherited from a group.',
    collection: false,
    keywords: ['admin', 'superadmin', 'permissions'],
  },
  {
    id: 'users.linkedObjects',
    path: '/api/v1/users/{userId}/linkedObjects/{relationshipName}',
    method: 'GET',
    group: 'users',
    summary: 'Manager or report relationships, which are links rather than profile fields.',
    collection: true,
    keywords: ['manager', 'reports', 'hierarchy'],
  },
  {
    id: 'users.sessions.delete',
    path: '/api/v1/users/{userId}/sessions',
    method: 'DELETE',
    group: 'users',
    summary: 'End every session this user holds. Sign-in is still permitted afterwards.',
    collection: false,
    keywords: ['signout', 'revoke', 'logout'],
  },
  {
    id: 'users.lifecycle.activate',
    path: '/api/v1/users/{userId}/lifecycle/activate',
    method: 'POST',
    group: 'users',
    summary: 'Move a STAGED user to ACTIVE, or to PROVISIONED when an activation email is sent.',
    collection: false,
  },
  {
    id: 'users.lifecycle.reactivate',
    path: '/api/v1/users/{userId}/lifecycle/reactivate',
    method: 'POST',
    group: 'users',
    summary: 'Restart activation for a PROVISIONED user whose email went unanswered.',
    collection: false,
  },
  {
    id: 'users.lifecycle.deactivate',
    path: '/api/v1/users/{userId}/lifecycle/deactivate',
    method: 'POST',
    group: 'users',
    summary: 'Deactivate the account. Clears group memberships and app assignments.',
    collection: false,
  },
  {
    id: 'users.lifecycle.suspend',
    path: '/api/v1/users/{userId}/lifecycle/suspend',
    method: 'POST',
    group: 'users',
    summary: 'Block sign-in while keeping memberships and assignments intact.',
    collection: false,
  },
  {
    id: 'users.lifecycle.unsuspend',
    path: '/api/v1/users/{userId}/lifecycle/unsuspend',
    method: 'POST',
    group: 'users',
    summary: 'Return a SUSPENDED user to ACTIVE.',
    collection: false,
  },
  {
    id: 'users.lifecycle.unlock',
    path: '/api/v1/users/{userId}/lifecycle/unlock',
    method: 'POST',
    group: 'users',
    summary: 'Clear a LOCKED_OUT status caused by failed sign-ins.',
    collection: false,
  },
  {
    id: 'users.lifecycle.resetPassword',
    path: '/api/v1/users/{userId}/lifecycle/reset_password',
    method: 'POST',
    group: 'users',
    summary: 'Start a password reset. Emails a one-time link, or returns one to hand over.',
    collection: false,
  },
  {
    id: 'users.lifecycle.expirePassword',
    path: '/api/v1/users/{userId}/lifecycle/expire_password',
    method: 'POST',
    group: 'users',
    summary: 'Force a password change at the next sign-in. The current password still works once.',
    collection: false,
  },
  {
    id: 'users.lifecycle.expirePasswordWithTempPassword',
    path: '/api/v1/users/{userId}/lifecycle/expire_password_with_temp_password',
    method: 'POST',
    group: 'users',
    summary: 'Expire the password and return a one-time temporary one in the response.',
    collection: false,
    keywords: ['temp', 'temporary', 'handover'],
  },
  {
    id: 'users.lifecycle.resetFactors',
    path: '/api/v1/users/{userId}/lifecycle/reset_factors',
    method: 'POST',
    group: 'users',
    summary: 'Unenrol every MFA factor, so the user enrols again at next sign-in.',
    collection: false,
    keywords: ['mfa', 'reset', 'reenroll'],
  },
] as const;

export default USER_ENDPOINTS;
