/**
 * Synthesise the advertisement's sound effects with ffmpeg.
 *
 *   node scripts/make-sfx.mjs            render every sound in sfx.json
 *   node scripts/make-sfx.mjs --check    fail if anything is missing or stale
 *
 * ## Why synthesis and not a sample library
 *
 * The reel already shells out to ffmpeg in three places, and ffmpeg's `lavfi`
 * sources can make every sound this ad needs: `sine` and `aevalsrc` for tones
 * and sweeps, `anoisesrc` for air and impact, and the `afade`/`lowpass`/`amix`
 * filters for the envelope that turns a tone into an event. That means the ad's
 * audio is a text file in the repo rather than seven binaries with a licence
 * history, it re-renders identically on any machine with ffmpeg, and changing
 * how the panel sounds when it arrives is a diff somebody can review.
 *
 * ## What it writes
 *
 * `captures/sfx/<id>.wav`, mono 48kHz, beside `captures/vo/` and for the same
 * reason: `remotion.config.ts` points the public dir at `../captures`, so
 * anything the composition plays has to live under it. `captures/` is
 * gitignored, so the WAVs are build output; the recipes are the source.
 *
 * Then `src/sfx.generated.ts`, which is how the composition knows what exists.
 * A missing WAV would fail a render deep inside Remotion with a message about a
 * URL; an id absent from the generated map simply renders that cue silent,
 * which is the behaviour a half-scored ad wants while it is being cut.
 *
 * @module
 */
import { execFile } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import prettier from 'prettier';

const run = promisify(execFile);

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REEL = path.resolve(HERE, '..');
const RECIPES = path.join(REEL, 'sfx.json');
const OUT_DIR = path.resolve(REEL, '../captures/sfx');
const GENERATED = path.join(REEL, 'src/sfx.generated.ts');

const check = process.argv.includes('--check');

/** Build one sound's ffmpeg argument list. */
function argsFor(id, recipe, out) {
  const args = ['-y', '-v', 'error'];
  if (recipe.complex) {
    for (const input of recipe.inputs) args.push('-f', 'lavfi', '-i', input);
    args.push('-filter_complex', recipe.complex, '-map', '[a]');
  } else {
    args.push('-f', 'lavfi', '-i', recipe.input);
    if (recipe.filter) args.push('-af', recipe.filter);
  }
  // Mono at 48kHz, matching `captures/vo/`. Remotion resamples anything else,
  // and a resample of a 50ms tick is audibly not the tick that was designed.
  args.push('-ac', '1', '-ar', '48000', out);
  return args;
}

/** What `ffprobe` measures a rendered file at, in seconds. */
async function measure(file) {
  const { stdout } = await run('ffprobe', [
    '-v',
    'error',
    '-show_entries',
    'format=duration',
    '-of',
    'csv=p=0',
    file,
  ]);
  return Number(stdout.trim());
}

async function main() {
  const { sounds } = JSON.parse(fs.readFileSync(RECIPES, 'utf8'));
  const ids = Object.keys(sounds);
  if (ids.length === 0) throw new Error('sfx.json declares no sounds.');

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const entries = [];
  for (const id of ids) {
    const recipe = sounds[id];
    const out = path.join(OUT_DIR, `${id}.wav`);

    if (check) {
      if (!fs.existsSync(out)) {
        console.error(`make-sfx: ${id}.wav is missing. Run \`npm run sfx\`.`);
        process.exitCode = 1;
        continue;
      }
    } else {
      await run('ffmpeg', argsFor(id, recipe, out));
    }

    const seconds = await measure(out);
    // A recipe states its own length and ffmpeg is told that length twice (in
    // the source's `d=`/`duration=` and in the filters' fade times), so a
    // mismatch means the two have drifted apart in the recipe itself. Worth
    // failing on: a sound half a second longer than the cut budgeted for it
    // plays over the next stab, and nothing else would report that.
    if (Math.abs(seconds - recipe.seconds) > 0.06) {
      console.error(
        `make-sfx: ${id} renders ${seconds.toFixed(3)}s but sfx.json says ${recipe.seconds}s. ` +
          `Fix the recipe's own duration, not this check.`,
      );
      process.exitCode = 1;
    }
    entries.push({ id, seconds });
    if (!check) console.log(`  ${id.padEnd(8)} ${seconds.toFixed(3)}s`);
  }

  if (check) {
    if (!process.exitCode) console.log(`sfx: ${ids.length} sounds present and the right length.`);
    return;
  }

  const body = entries
    .map(({ id, seconds }) => `  ${id}: { file: '${id}.wav', seconds: ${seconds} },`)
    .join('\n');

  const source = `/**
 * @module reel/sfx.generated
 * @description The advertisement's rendered sound effects.
 *
 * GENERATED by \`scripts/make-sfx.mjs\` from \`sfx.json\`.
 * Do not edit. Read this through \`sfxClip\` in \`ad/sfx.ts\`, never directly.
 */

/** Sound id -> the WAV that was rendered for it, and its measured duration. */
export const SFX = {
${body}
} as const;
`;

  const options = await prettier.resolveConfig(GENERATED);
  const formatted = await prettier.format(source, { ...options, filepath: GENERATED });
  fs.writeFileSync(GENERATED, formatted);
  console.log(`Wrote ${entries.length} sounds and ${path.relative(REEL, GENERATED)}.`);
}

main().catch((error) => {
  console.error(error.message ?? error);
  process.exit(1);
});
