/**
 * Measure every recorded narration WAV and write `src/vo.generated.ts`.
 *
 *   node scripts/measure-vo.mjs
 *
 * `captures/vo/<act-key>.wav` is where Sam drops his recordings, one per act
 * (`NARRATION.md` states the naming rule). This probes each one with
 * `ffprobe`, the same ffmpeg the capture rig already shells out to (see
 * `.storybook/scripts/capture/screencast.mjs`, `check.mjs`), for its exact
 * duration, and writes the result as a generated literal, the same pattern
 * `sync-theme.mjs` uses for the app's design tokens: committed, so a render or
 * a `vo.ts` import never depends on having run this first, and regenerated
 * from the one source of truth rather than hand-maintained.
 *
 * Idempotent: run it as many times as you like against the same
 * `captures/vo/`. The output is a pure function of the WAVs on disk.
 *
 * @module
 */
import { execFile } from 'node:child_process';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
import prettier from 'prettier';
import { VO_DIR, VO_GENERATED_TS } from './lib/paths.mjs';

const run = promisify(execFile);

/** `ffprobe`'s duration for one file, in seconds, rounded to a hundredth. */
async function probeSeconds(file) {
  let stdout;
  try {
    ({ stdout } = await run('ffprobe', [
      '-v',
      'error',
      '-show_entries',
      'format=duration',
      '-of',
      'default=noprint_wrappers=1:nokey=1',
      file,
    ]));
  } catch (err) {
    throw new Error(`measure-vo: ffprobe could not read ${file}: ${err.message}`);
  }
  const seconds = Number(stdout.trim());
  if (!Number.isFinite(seconds)) {
    throw new Error(
      `measure-vo: ffprobe returned no usable duration for ${file}: "${stdout.trim()}"`,
    );
  }
  return Math.round(seconds * 100) / 100;
}

async function main() {
  const files = (await readdir(VO_DIR).catch(() => [])).filter((f) => f.endsWith('.wav')).sort();

  const entries = [];
  for (const file of files) {
    const key = file.slice(0, -'.wav'.length);
    const seconds = await probeSeconds(path.join(VO_DIR, file));
    entries.push([key, { file, seconds }]);
  }

  const body = entries
    .map(
      ([key, { file, seconds }]) =>
        `  ${JSON.stringify(key)}: { file: ${JSON.stringify(file)}, seconds: ${seconds} },`,
    )
    .join('\n');

  const out = `/**
 * @module reel/vo.generated
 * @description Measured narration durations, one entry per recorded act.
 *
 * GENERATED by \`scripts/measure-vo.mjs\` from \`captures/vo/*.wav\`.
 * Do not edit. Read this through \`voClip\`/\`voMeta\` in \`vo.ts\`, never directly.
 */

/** Act key -> the WAV \`ffprobe\` measured for it, and its duration in seconds. */
export const VO = {
${body}
} as const;
`;

  // Formatted before writing, and via `prettier.resolveConfig` rather than a
  // bare `format()` call, for the exact reason `sync-theme.mjs` documents:
  // `format()` does not read `.prettierrc` on its own, so skipping this step
  // means `npm run format` immediately reformats the file right back.
  const prettierOptions = await prettier.resolveConfig(VO_GENERATED_TS);
  const formatted = await prettier.format(out, { ...prettierOptions, filepath: VO_GENERATED_TS });

  await writeFile(VO_GENERATED_TS, formatted);
  console.log(`${entries.length} narration file(s) -> src/vo.generated.ts`);
}

try {
  await main();
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
