/**
 * Mirror the app's design tokens into the composition.
 *
 *   node scripts/sync-theme.mjs
 *
 * The reel renders outside the extension: no Tailwind, no `@theme`, no
 * `var(--color-primary)`. But `CLAUDE.md`'s "no raw hex" rule exists because a
 * hand-copied palette drifts, and a reel whose brand blue is one shade off the
 * product's is worse than one with no brand blue at all.
 *
 * So the palette is *generated* rather than transcribed. This reads
 * `src/sidepanel/tailwind.css` — the single definition — and writes
 * `src/theme.generated.ts`. The generated file is committed so a render never
 * depends on having run this, and `--check` fails when the two have diverged,
 * which is what CI asserts.
 *
 * @module
 */
import { readFile, writeFile } from 'node:fs/promises';
import prettier from 'prettier';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SOURCE = path.resolve(HERE, '../../src/sidepanel/tailwind.css');
const DEST = path.resolve(HERE, '../src/theme.generated.ts');

const css = await readFile(SOURCE, 'utf8');

/** `--color-primary: #546be7;` → `['color-primary', '#546be7']`, comments stripped. */
const tokens = [...css.matchAll(/^\s*--([\w-]+):\s*([^;]+);/gm)].map(([, name, value]) => [
  name,
  value.replace(/\/\*[\s\S]*?\*\//g, '').trim(),
]);

const group = (prefix) =>
  tokens
    .filter(([name]) => name.startsWith(`${prefix}-`))
    .map(([name, value]) => [name.slice(prefix.length + 1), value]);

const emit = (name, pairs) =>
  `export const ${name} = {\n${pairs
    .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
    .join('\n')}\n} as const;\n`;

const colors = group('color');
const durations = group('dur');
const eases = group('ease');
const fonts = group('font');

if (colors.length < 10) {
  throw new Error(`sync-theme: only ${colors.length} colours parsed — the @theme block moved?`);
}

const out = `/**
 * @module reel/theme.generated
 * @description The app's design tokens, mirrored for the composition.
 *
 * GENERATED by \`scripts/sync-theme.mjs\` from \`src/sidepanel/tailwind.css\`.
 * Do not edit. Reel-only values belong in \`theme.ts\`, which re-exports this.
 */

${emit('COLOR', colors)}
${emit('DUR', durations)}
${emit('EASE', eases)}
${emit('FONT', fonts)}`;

// Formatted before it is written *and* before it is compared, because the
// alternative is a gate that can never be green. `npm run format` prettifies
// everything under the repo, `theme.generated.ts` included, so raw generator
// output and the committed file differ in quotes and key quoting from the first
// time anybody runs it. `--check` then reports "stale" forever, on a file whose
// tokens are identical - and a gate that is always red is worth exactly as much
// as one that is always green. Measured: it had been red since PR #101, which
// is also how four real missing tokens went unnoticed underneath the noise.
// `resolveConfig` explicitly, not just `filepath`: `format()` takes the parser
// from the path but does *not* read `.prettierrc` on its own, so without this
// the generator formats to prettier's defaults and `npm run format` immediately
// reformats it back - the same permanent-red loop, one layer down.
const prettierOptions = await prettier.resolveConfig(DEST);
const formatted = await prettier.format(out, { ...prettierOptions, filepath: DEST });

if (process.argv.includes('--check')) {
  const existing = await readFile(DEST, 'utf8').catch(() => '');
  if (existing !== formatted) {
    console.error('reel/src/theme.generated.ts is stale — run `node scripts/sync-theme.mjs`');
    process.exit(1);
  }
  console.log('theme is in sync');
} else {
  await writeFile(DEST, formatted);
  console.log(`${colors.length} colours, ${durations.length} durations → src/theme.generated.ts`);
}
